home/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("", views.home_page, name="home-page"),
    path("updateabout/<int:pk>/", views.UpdateAboutPage.as_view(), name="update-about-page"),
    path("login/", LoginView.as_view(template_name="home/login.html"), name="login-page"),
    path("logout/confirmation/", views.LogoutConfirmationView.as_view(), name="logout-confirmation-page"),
    path("logout/", LogoutView.as_view(template_name="home/logout_success.html"), name="logout-page"),
]

portfoliosite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('posts/', include("posts.urls")),
    path('skills/', include('skills.urls')),
    path('education/', include("education.urls")),
    path('messages/', include("messages.urls")),
    re_path(r'^(?P<path>.*)$', views.page_not_found, name="page-not-found")
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("all/<type>/", views.AllPosts.as_view(), name="all-posts-page"),
    path("create/", views.CreatePost.as_view(), name="create-post-page"),
    path("update/<int:pk>/", views.UpdatePost.as_view(), name="update-post-page"),
    path("singlepost/<pk>/", views.single_post, name="single-post-page"),
    path('delete/<pk>/', views.DeletePost.as_view(), name="delete-post-page"),
    path("newimage/", views.UploadImage.as_view(), name="upload-image-page"),
    path("allimages/", views.AllImages.as_view(), name="all-images-page")
]

posts/models.py
from django.db import models


post_choices = [
    ("blog", "Blog"),
    ("project", "Project")
]


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    type = models.CharField(max_length=10, choices=post_choices, default="blog")

    def __str__(self):
        return f"{self.title} - {self.type}"


class ImageObj(models.Model):
    purpose = models.CharField(max_length=30)
    source = models.ImageField(upload_to="all_images")
    date_uploaded = models.DateTimeField(auto_now_add=True)

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class AllPosts(ListView):
    template_name = "posts/all_posts.html"
    context_object_name = "all_posts"
    model = models.Post
    ordering = "-last_updated"
    paginate_by = 10

    def get_queryset(self):
        query_by = self.kwargs.get("type")
        query_set = models.Post.objects.order_by("-last_updated").filter(type=query_by)
        return query_set


class CreatePost(LoginRequiredMixin, CreateView):
    model = models.Post
    fields = ["title", "content", "type"]
    template_name = "posts/create_post.html"
    success_url = reverse_lazy('all-posts-page', kwargs={"type": "blog"})


class UpdatePost(LoginRequiredMixin, UpdateView):
    model = models.Post
    fields = ["title", "content", "type"]
    template_name = "posts/create_post.html"
    success_url = reverse_lazy("all-posts-page", kwargs={"type": "blog"})


def single_post(request, pk):
    post = models.Post.objects.get(pk=pk)
    context = {"post": post}
    return render(request, "posts/single_post.html", context=context)


class DeletePost(LoginRequiredMixin, DeleteView):
    model = models.Post
    success_url = reverse_lazy('all-posts-page', kwargs={"type": "blog"})


class UploadImage(LoginRequiredMixin, CreateView):
    model = models.ImageObj
    fields = "__all__"
    success_url = reverse_lazy("all-images-page")
    template_name = "posts/upload_image.html"


class AllImages(LoginRequiredMixin, ListView):
    model = models.ImageObj
    template_name = "posts/all_images.html"
    context_object_name = "all_images"
    paginate_by = 10

posts/templates/posts/all_images.html
{% extends 'home/base.html' %}
{% load static %}
{% load extras %}
{% block content %}
<div class="upload-image-page-content hidden">
    {% for image_obj in all_images %}
    <div class="single-image-details-container">
        <img src="{{ image_obj.source.url }}" class="single-image-photo">

        <div class="single-image-details">
            <p>Purpose: {{ image_obj.purpose }}</p>
            <p>Date Posted: {{ image_obj.date_posted }}</p>
            <p class="img-url" tooltip="Click to Copy" onclick="navigator.clipboard.writeText('{{ image_obj.source.url | parse_aws_url }}')">Image URL: {{ image_obj.source.url | parse_aws_url }} </p>
        </div>
    </div>
    {% endfor %}
</div>

<div class="pagination">

    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}" class="pagination-arrow-link"> <img src="{% static 'icons/previous-page.svg' %}" class="pagination-arrows"> </a>
    {% endif %}

    <span class="pagination-current-page">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="pagination-arrow-link"> <img src="{% static 'icons/next-page.svg' %}" class="pagination-arrows"> </a> </div>
    {% endif %}

</div>

{% endblock content %}

posts/templates/posts/all_posts.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="post-page-content hidden">

    {%  for post in all_posts %}
    <a href="{% url 'single-post-page' pk=post.pk %}">
        <div class="individual-post">
            <h4 class="individual-post-heading">{{ post.title }}</h4>
            <p class="individual-post-preview">{{ post.content | truncatewords:40 }}</p>
            <p class="individual-post-date">Last Updated: {{ post.last_updated |date:"Y-m-d" }}</p>
            <img src="{% static 'icons/arrow.svg' %}" class="post-arrow-icon">
        </div>
    </a>
    {% endfor %}

</div>
<div class="pagination">

    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}" class="pagination-arrow-link"> <img src="{% static 'icons/previous-page.svg' %}" class="pagination-arrows"> </a>
    {% endif %}

    <span class="pagination-current-page">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="pagination-arrow-link"> <img src="{% static 'icons/next-page.svg' %}" class="pagination-arrows"> </a> </div>
    {% endif %}

</div>

{% endblock content %}

posts/templates/posts/create_post.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

<div class="create-post-page-content hidden">
    <div class="create-post-page">
        <div class="create-post-page-section" style="border-right: 1px solid black ;">
            <form class="create-post-form" method="POST">
                {{ form }}
                {% csrf_token %}
                <button>Submit</button>
            </form>
        </div>
        <div class="create-post-page-section">
            <div id="single-post-page-content" class="single-post-page-content"></div>
        </div>
    </div>
</div>
<script src="{% static 'javascript/showdown.js' %}" defer></script>
<script src="{% static 'javascript/prism.js' %}" defer></script>
<script defer>
/*
This script updates the preview window as you create a new post.
On the initial load, the input is put into paragraph tags for styling purposes.
Subsequent updates will grab the contents of the textarea and convert it from markdown to HTML,
thereby enclosing it in the paragraph tags that are needed to style it.
*/
let preview = document.querySelector(".single-post-page-content");
let postTextInput = document.querySelector(".create-post-form textarea");
preview.innerHTML = "<p>" + postTextInput.value + "</p>";

postTextInput.addEventListener("input", () => {renderHtml('.single-post-page-content')})
document.querySelector("#id_title").addEventListener("input", () => renderHtml(".single-post-page-content"))

</script>
{% endblock content %}

posts/templates/posts/single_post.html
{% extends 'home/base.html' %}
{% load static %}
{% load extras %}
{% block content %}

<div id="single-post-page-content" class="single-post-page-content">
    <form id="csrf-token-container">
        {% csrf_token %}
    </form>

    <h1>{{ post.title }}</h1>
    {{ post.content | mdconverter | safe}}

</div>
{% if user.is_authenticated %}
<div class="crud-page-contorl-button-container">
                <a href="{% url 'create-post-page' %}"><img src="{% static 'icons/new_icon.svg' %}" class="crud-page-contorl-button"></a>
                <a onclick="postDeleteConfirmation(event, {{post.id}})"><img src="{% static 'icons/delete_icon.svg' %}" class="crud-page-contorl-button"></a>
                <a href="{% url 'update-post-page' pk=post.id %}"><img src="{% static 'icons/edit_icon.svg' %}" class="crud-page-contorl-button" ></a>
</div>
{% endif %}
<script defer src="{% static 'javascript/showdown.js' %}"></script>
<script defer>
/*
These variables are needed in the JavaScript file "app.js" to initiate and confirm the deletion of a Post object.
Django does not support templating variables in standalone JavaScript files, therefore, variables from the server
must be rendered into script tags within the html file and then referenced in app.js.
*/
let xBtn_url = "{% static 'icons/x_icon.svg' %}"
/*
The postDeleteUrl is spliced because the route requires a URL parameter and omitting a parameter will throw an error.
To solve this, we pass "1" to the "pk" it is expecting anf then spice the string to cut the parameter out.
*/
let postDeleteUrl = "{% url 'delete-post-page' pk=1%}".slice(0, -2)
</script>

{% endblock content %}

posts/templates/posts/upload_image.html
{% extends 'home/base.html' %}
{% block content %}
<div id="upload-image-page-content" class="upload-page-content hidden">
    <h3 class="page-heading">Upload new Image </h3>
    <div class="upload-image-page-form-container">
        <form method="POST" enctype="multipart/form-data">
            {{ form }}
            {% csrf_token %}
            <button>Upload</button>
        </form>
    </div>
</div>
{% endblock content %}